### PR TITLE
Display duration and end time for non-recurrent program with idd

### PR DESCRIPTION
**Pull request by embak**
Improve program list summary by the displaying total duration and end time when non-recurrent and individual station duration.

### CODE REVIEW

**Comment by Dan-in-CA** [comment]
Looks like new settings are not being saved when an existing program is edited.

**Comment by embak** [comment]
Just verified and program.json is updated with the proper values when modifications are made to programs (from modify.html) or programs are enabled/disabled (from program.html).  Also tested with options seq and idd turned on/off.

**Comment by Dan-in-CA** [comment]
Thanks.
I updated the version of SIP on my test rig and it seems to be working as expected.

Thanks again for your contributions to the SIP project.

Dan

**Comment by Dan-in-CA** [comment]
Well there is a bug.

If I try to set a program to run a single pass the program summary sows the program a recurring. If I try to edit the program the change to single pass does not get saved.

I set 2 stations to run for 45 min and 2 to run for 60 min. When I clicked the Run Now button all 4 stations started running for 15 min each. not what they are set for.

**Comment by embak** [comment]
What are your stations handling options (sequential, individual duration) ?

**Comment by Dan-in-CA** [comment]
Not your fault.

I have been testing older versions and the bug goes back several versions before you made your changes.

**Comment by embak** [comment]
> If I try to set a program to run a single pass the program summary sows the program as recurring. If I try to edit the program the change to single pass does not get saved.
>
This behavior was introduced a long time ago. #184 should have corrected this behavior.
What is your start time and how many stations and individual duration durations

**Comment by Dan-in-CA** [comment]
Setting start time to 1 minute after now shows the problem. This is with 4 stations, 2 at 45 min and 2 at 60 min.

**Comment by Dan-in-CA** [comment]
It only runs with the wrong durations when the "run now" button is clicked.
If it runs from the set start time the durations are correct.

**Comment by embak** [comment]
I got it on my side also.
With individual station duration:  should program[6] == sum( station duration)
or be left as is ?

**Comment by Dan-in-CA** [comment]
Good question.
That value existed before idd was added. It is used when idd is off. It might be good to show the full duration when idd is on but it might be good to keep the sum in a separate var.

**Comment by embak** [comment]
From my understanding, "general duration" a.k.a program[6] should be left intact.  Too much side effect when flipping the idd option.  Also keeping the sum in a separate var could lead to other problems if we want to do individual water duration adjusts.  Better to redo the sum as needed.

With #184 my attempt was to correct a rounding problem between "general duration" (in minutes) and "individual duration" (in minutes + seconds), but it appears that the "recurrent" detection test wasn't adjusted to take idd into account.
Regarding the "run now" it seems to be another side effect of idd introduction.
I will look at it this evening.

I wonder how recurrent programs behaves with idd ?

**Pull request merged**
