### PR TITLE
Addition of RHEL/Fedora/Centos SystemD service file

### PR DESCRIPTION
**Pull request by mekenthompson**

### CODE REVIEW

**Comment by Dan-in-CA** [comment]
Thanks Ken,

As of September 24, 2015 the official Raspberry Pi site has Debian Jessie as the latest OS version for download. Raspbian Jessie also uses systemd as the default init system. it looks like your files should work with that distro. I have a Pi with Jessie installed and will test your contribution. It will also be necessary to write some user docs for the SIP wiki on how to use the files.

It may take me a day or so to test and merge your pull request.

Dan

**Comment by mekenthompson** [comment]
No problems; I have some notes somewhere on enabling it (the systemd service). I can collate these and add to the wiki also and some further comments in the file about this.

**Comment by Dan-in-CA** [comment]
OK, 
Your sip.service file works with Raspbian Jessie.

There is one problem with the pull request though:
There is a modified version of **sip.sh** which is not needed for **sip.service** to work but the changes make the file unusable for it's original purpose of providing an **init.d script** for those users on Raspbian Wheezy or any distro that uses init.d for auto-start.

I will merge your pull request and then push a copy of the original sip.sh file to the repo.

Also, there are some other issues that need to be addressed when using Raspbian Jessie and I am working on documentation for the wiki to cover those. I will include instructions for using the sip.service file.

Thanks again.
Dan

**Comment by mekenthompson** [comment]
Yeah, not sure how that happened, I forked from your master only the other day and hadn't changed those files myself...first pull request I've done on GitHub, thanks for sorting out your end. I'll re-sync from your master.

**Pull request merged**
