### PR TITLE
Make data directory location configurable via $SIP_DATA_DIR env var

### PR DESCRIPTION
**Pull request by dannf**
I've been playing with create a snap (http://snapcraft.io) of this project. One issue I hit there is that snaps can only write under a specific directory. This adds an environment variable to specify a writeable location (e.g. in the snap i set SIP_DATA_DIR=$SNAP_DATA). When SIP_DATA_DIR is not specified, it still falls back to "."

With this I have a working snap running on my BeagleBone Black - after some cleanup, I'll share a branch w/ the snap bits as well.

### CODE REVIEW

**Comment by Dan-in-CA** [comment]
This looks very interesting!
Let me do some testing before merging it.
GitHub says there are conflicts and it can't be merged yet.

It might be better to put all the changes into the branch you are working on.

It seems like it will improve security but SIP is intended to be easy for users to modify and experiment with the code. From the snapcraft website:

"Snaps are read-only for security. We want to prevent a hostile party from sneakily changing the software on your machine, so you cannot modify a snap that is installed on your system."

If users can select a branch to install the snap from that would be good. Users that just want a secure installation could in stall the snap. Users that want to tinker with the code could install the 'regular" version.

Would the 'system update' plugin still work under snap?

Dan

**Comment by Dan-in-CA** [comment]
I cloned a copy of your fork and checked out the SIP_DATA_DIR branch but when I try to run it there is a JSON error and non of the config files are created.

**Comment by Dan-in-CA** [comment]
Most SIP users are on Raspberry Pi. 
I tried installing snapd on a Pi with the latest OS (jessie) using apt install snapd and got an error: "Unable to locate package snapd" This could be a real problem for most users. SIP was designed from the start to be super easy to install - just clone from GitHub and run. No compiling or other installation involved.

what OS are you running on your Beagle Bone?

**Comment by Dan-in-CA** [comment]
Upon further investigation I found that there is a "snapy ubuntu" OS image for the Raspberry Pi that supports snaps. However it only works on older Pi 2s not the latest Pi 3 (I tried it)). It is still in an early stage of development and It doesn't look like it is ready for general use. I had to install Python as a separate step and then couldn't import  the standard GPIO library.

**Comment by dannf** [comment]
hey Dan!
I'll look into the conflict today, apologies for that. Meanwhile, let me address some of your other questions.

The lack of python/gpio lib in the OS snap is by design - application snaps provide their own dependencies. That way, no matter what OS the end-user is running, you can ensure they are using the same python version/binary and library snapshots that you tested with. 

See the adafruit part here to see how that is done:
https://github.com/dannf/SIP/blob/snapcraft/snapcraft.yaml

I pushed my test snap up to the snap store under my namespace if you wanna try it on your Pi:

snap install opensprinkler-sip-dannf --devmode --channel edge

My BBB is running Ubuntu 16.04 in "classic" Ubuntu mode (deb-based install). I'm using the 4.1-based kernel w/ security=apparmor on the cmdline, since apparmor is what snapd uses for confinement. I think the Pi(2) is a more practical target for this work since there is an OS snap for it - but I don't have one to test on.

**Comment by Dan-in-CA** [comment]
Great! 

I didn't intend to discourage you when I was encountering problems on the Pi. As you can tell I am not familiar with snap architecture yet but it looks very promising especially the security and auto-update aspect. 

I will test your snap on a Pi 2. If it works well I will make an announcement on the SIP forum. It will also be necessary to add some documentation to the SIP wiki.

I still have some questions regarding the plugin manager. I will test installing and activating a plugin from the snap and see what happens.

**Comment by Dan-in-CA** [comment]
Aargh!

Taking another look at ubuntu snap on a Pi 2. When I try to install the first snap it is supposed to install ubuntu-core as a snap. After downloading the snap it raises an error.

error: unable to perform the following tasks:
- make snap 'ubuntu-core" available to the system (cannot set next boot, cannot determine bootloader)

If I run 'snap list" it gives an error "no snaps found"

I even set up an ubuntu account so I can log into the snap store but no-go.

Also downloaded and set up Ubuntu 16.04 LTS MATE which does run on the Pi 3 and is supposed to support snaps - same problem on both Pi 2 and Pi 3.

**Comment by dannf** [comment]
I rebased my branch on the latest trunk, but noticed that on checkout the new .gitattributes file was causing eol conversions. I suspect the impacted files need to be committed w/ the settings defined in .gitattributes to avoid that. I'm not 100% sure, so just added a revert commit here to avoid making unrelated changes.

I tested this in non-snap mode on my BBB and didn't observe any JSON errors.

**Comment by dannf** [comment]
Dan - can you elaborate on how you are installing the snap - i.e., what command is emitting that error message? I haven't done it myself, but it looks like the recommended installation process is to blit an image to disk w/ snappy pre-installed:
  https://developer.ubuntu.com/en/snappy/start/raspberry-pi-2/

I'm running my BBB on ubuntu classic (apt-based), w/ snapd installed on top, so it's not a pure snap system. In this config, I don't think snappy tries to manage the bootloader - is that what you're doing with MATE?

fyi, snap list on my system just shows snaps that are already installed, so "no snaps found" maybe what you *should* see if no snaps are installed. 'sudo snap install hello' should get you a simple hello world snap.

**Comment by Dan-in-CA** [comment]
I followed the instructions on the ubuntu web site that your link points to. 
My first try was to image the SD card with the image linked from that site. I am running Windows 7 on my desktop.

Everything went fine until I tried to do "sudo snap install hello". The download of ubuntu-core completed without a problem until the error message appeared:
"error: unable to perform the following tasks:
    make snap 'ubuntu-core" available to the system (cannot set next boot, cannot determine bootloader)"

I followed pretty much the same procedure with ubuntu Mate ( except I had to use a 16GB card). I also tried "sudo apt install snapd" and got a message that it was already installed. Then I tried "sudo snap install hello" and the exact same error occurred after the download of ubuntu-core finished. I tried this SD card on both a Pi 2 and a Pi 3.

I have also googled for a solution without much luck.

**Comment by Dan-in-CA** [comment]
Regarding the .gitattributes file. It is supposed to cause GitHub to always serve file with unix style EOLs.
I added it in response to this old issue:
https://github.com/Dan-in-CA/SIP/issues/134

**Comment by Dan-in-CA** [comment]
Looks like there was a bug in ubuntu:
https://bugs.launchpad.net/snappy/+bug/1580403

I am running an update. We'll see what happens.

**Comment by dannf** [comment]
On Mon, Aug 22, 2016 at 06:15:58PM -0700, Dan wrote:
> Regarding the .gitattributes file. It is supposed to cause GitHub to
> always serve file with unix style EOLs.

Oh - ok. If that's the goal, then I think we just need to refresh the
files on master to have unix style EOL's that match the .gitattributes
file. I'll prepare a branch and see if it works for you.

  -dann

**Comment by Dan-in-CA** [comment]
After updating ubuntu mate the snap installation got pased the ubuntu-core installation but then:

"Setup snap "hello-world" (27) security profiles (cannot load apparmor profile "snap.hello-world.env": cannot load apparmor profile: exit status 1
apparmor_parser output:
Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)
Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.)"

Tried "sudo apt-get source apparmor" as suggested on the web but it is still not working.

**Comment by dannf** [comment]
I hit the same thing, because I'm not using an Ubuntu kernel. Adding security=apparmor to the kernel command line fixed it.

**Comment by Dan-in-CA** [comment]
I have been trying to find out how to add to the kernel command line. 
All the instructions I have found so far do not work on the ubuntu mate installation I have. They refer to editing the file /etc/default/grub but that file does not exist. I looked in the directory and it is definitely not there. I tried rebooting and holding down the shift key as most instructions say but it does not bring up the grub menu.

Any ideas?

**Comment by Pelado-Mat** [comment]
This change would impact also all the plugins, as they also save data in the data dir.

Perhaps a new global in gv.py could be created to share the location of the datadir.

**Comment by Dan-in-CA** [comment]
After trying to implement snap on the Pi it looks like this will not be feasible for most SIP users at this point in time.

**Pull request closed without merging**
