### PR TITLE
Correct individual station duration side effects

### PR DESCRIPTION
**Pull request by embak**
For individual station duration, and in complement to #186 and #184 this:
- correct the calculation of the "recurrent" status in programs.html and modify.html,
- properly schedule the program "run now" (webpages.py),
- improve the starting and recurring status programs display.

### CODE REVIEW

**Comment by embak** [comment]
Just figured out that in "concurrent running mode" the total program duration with or without idd will not be right.  This will also affect the "recurring" detection. Will be corrected tomorrow.

**Comment by embak** [comment]
Program duration and "recurring" detection in "concurrent running mode" with or without idd is now working.

**Comment by Dan-in-CA** [comment]
Fantastic! 
I greatly appreciate your work on this. I won't have time to do extensive testing until later today but it is looking good so far.

There is still a problem if a program with idd is created with a setting of "single pass" and then it is changed to "recurrent" the change does not take.

**Comment by embak** [comment]
This is normal if you don't change the program end time.  Is-it the case ?

Since there is no program variable to store the "single pass" vs "recurring" mode, the detection is based on the calculation of program's single lap duration vs the stored program end - start time:
So :   recurring = (start_time + lap_duration ) < end_time

P.S: I am currently working on implementing feature request #175.  I will need some advise when implementing the changes on modify.html.  I will let you know.

**Pull request merged**
