### PR TITLE
Odroid-C2 board support

### PR DESCRIPTION
**Pull request by egisz**
Hi, I've added support for Odroid-C2 board. It has slightly different wiringPi interface.

### CODE REVIEW

**Comment by Dan-in-CA** [comment]
Thank you.

I will take a look at your code changes.

I will need to give this some thought.

It looks like the Odroid-C2 board can not be purchased now due to the unavailability of parts:
http://www.hardkernel.com/main/products/prdt_info.php?g_code=G145457216438

Are you willing to provide user support for this board to SIP users? If so, how can they contact you?

If you can combine the odroid specific code into a plugin that is separate from the relay_board plugin that would be preferable.

Dan

**Comment by egisz** [comment]
Hi Dan,

I am using SIP project for irrigating and yard lighting for around 2 years. Very nice work!

Today I found and fixed small bug in gpio_pins.py (my own bug, late evening work :). 
Today I tested on Raspberry Pi3 (in combination with relay_board plugin) and it now works fine. I don't yet have shift registers, but plan to build next week and test if it works too.
I did not test rain sensor, because I don't have it...

This Pull request does not affect relay_board plugin. It only takes care of shift registers. I've created another pull request for relay_board in sip_plugins repo.

I would be glad to help other ODROID-C2 users, as I plan to use this board myself for watering and NAS project. I'm not yet sure how it would be best to communicate, I could monitor subscribe and respond to issues on your repository.

Dan

**Comment by Dan-in-CA** [comment]
I have been doing some testing of your version from your repo and it seems to be working fine.

Some users have also been interested in running SIP on Orange Pi (another Pi clone) and SIP has supported the Beagle Bone Black board from the start.

One of the goals of the SIP project is to keep things as simple as possible to make it easy for users to modify the code. I have decided to merge your pull request into a branch for the Odroid-C2 rather than into the master branch. There is already a branch for the Orange Pi although it is not usable at this point. I also plan to make a branch for the Beagle Bone Black. This will help to keep the code from getting bloated. This will also simplify the addition of other boards in the future 

The branches can be kept in sync by applying bug fixes/minor updates as patches to each branch rather than merging

**Comment by Dan-in-CA** [comment]
Merged

**Comment by egisz** [comment]
Thanks for merge!

I have idea how to separate different boards logic in object oriented way:
There could be created one abstract class for GPIO pins, which would define necessary methods that are required to be implemented, such as: set usable pins, write high or low values to pins, read data from pins.
Then, for each board, there would be separate class that inherits from this abstract class and implements methods, 
Finally, after detection of board type, SIP could create object for correct board and use it for all GPIO operations.

**Comment by Dan-in-CA** [comment]
Your idea sounds very interesting.
Could you make example code for testing?

**Pull request merged**
