### PR TITLE
Change spelling

### PR DESCRIPTION
**Pull request by Noschvie**

### CODE REVIEW

**Comment by Dan-in-CA** [comment]
Thank you for the language update.

**Comment by Noschvie** [comment]
BTW: why all the text at the GUI uppercase? Can this be changed easily to have the message text as defined in the language file? Thanks

**Comment by Dan-in-CA** [comment]
Only the text on clickable buttons is uppercase. It helps to show users what the active elements of the UI are.
Do you have a reason for wanting the button text to be mixed case?

**Comment by Noschvie** [comment]
Hi Dan,
for me the GUI is extraordinary, such buttons with uppercase text never seen before.

**Pull request merged**
