### PR TITLE
add debian packaging

### PR DESCRIPTION
**Pull request by nivw**
this pull is simpler

### CODE REVIEW

**Comment by Dan-in-CA** [comment]
I'll close the first pull request.
I am also in the process of renaming the project from OSPi to SIP and would prefer to not to do any merges until after the name change is done.

**Comment by Dan-in-CA** [comment]
The project has now been renamed from ospi to sip. It looks like the requested pull will need to be updated.

Also, I am wondering what advantage this will add to the project and how will it affect the operation of plugins especially the system_update plugin.

One of the main goals of this project is to make it easy to modify by users who may not be experienced programmers. The documentation is based on an installation from a GitHub clone. would that need to be changed?

**Comment by nivw** [comment]
Hi Dan?
I moved to use debian 8.0 and 8.1 with recent kernels 4.0.4 and 4.1.
then I want to easily install OSPi so installing a deb file is easy.
Also, I see you include blinker, while if using a deb file you can tell
your package depends on python-blinker, and it will be pulled and
installed for you.
Also upgrades are easy this way.

I also find your use of running the program as root on a device, not a
good idea, as a hacker can use it to take control of the device. and as
it is in your home network, he can infect other devices. But hay I am
just this guy that works in the computer security business.

Thanks a lot for the code and do hope to see it evolve. where are all of
you located int he world? any chance to meet?
Niv

On Fri Aug 7 01:24:09 2015 GMT+0300, Dan wrote:
> The project has now been renamed from ospi to sip. It looks like the requested pull will need to be updated.
> 
> Also, I am wondering what advantage this will add to the project and how will it affect the operation of plugins especially the system_update plugin.
> 
> One of the main goals of this project is to make it easy to modify by users who may not be experienced programmers. The documentation is based on an installation from a GitHub clone. would that need to be changed?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Dan-in-CA/SIP/pull/111#issuecomment-12852654

-- 
Sent from my Jolla

**Comment by Dan-in-CA** [comment]
Hi Niv,
I am definitely interested in your proposal and security is a priority.

I do still have some concerns about how it will affect the work flow and things like users being able to update the software from the UI.

As it is now when there is an update or a pull request it is easy to just do a push or a couple of clicks to accept a pull request. What steps would be needed to build a deb package and where would that package be kept?

Would it be possible to have both a deb package install and also be able to clone from GhiHub? 
I like the idea of having the package install manage dependencies.

**Comment by ndesimone** [comment]
I don't like the idea of running as root either, and am working on changes to sip.sh to address that.

**Comment by mihugo** [comment]
ndesimone:  if it helps see my comments from #116 about how I run as a non-root user.   (basically just a few hacks to the init script to change effective UID when python is started).  Since I'm using a non-privilege port it is fairly straightforward and the restart command still works.

I didn't take the time to figure out how to do a fork in python after port 80 is opened but before the main loop is started (os.setuid) which could be a better way of doing it and how webservers work.  Speaking of webservers it might just be interesting to look into what it would take to go the wSGI route but then that could be a rat hole in itself.  I like how simple Dan's design is.

Also dabbling in the security world I am of 2 minds of how big of a deal it is to run with a non-root for an embedded device.  If we are being paranoid IOT devices should be on their own network anyways.

**Comment by Dan-in-CA** [comment]
Looking at mihugo's comments in #116, Looks like he is not using the RPi.GPIO Python library that is included in the Raspbian OS. That library can only be run as root.

There is an alternative library, pigipo, which can be run by a non-root user. Brian has modified the core program to be able to use that as an option.

See
http://abyz.co.uk/rpi/pigpio/index.html
for installation information.

**Comment by Dan-in-CA** [comment]
It does not look like this request will be updated so I will close the pull request.
The requirement of running as root has been removed in raspbian Jessie. as long as the port is set to something above 1024. You can set a user option in the sip.service unit file.

**Pull request closed without merging**
